### ISSUE TITLE
Bug: non-responsive package org.hsql.jdbc in an AppMap recorded from a Java WebApp

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-js#206]
Package org.hsql.jdbc cannot be selected or expanded in the Dependency Map

AppMap file: https://app.land/api/scenarios/3b14b4b8-1e07-438e-86ca-acf42c69f527
AppMap: https://app.land/scenarios/3b14b4b8-1e07-438e-86ca-acf42c69f527?state=%257B%2522currentView%2522%3A%2522viewComponent%2522%257D

appmap.yml:
```yaml
name: bodgeit
packages:
  - path: org.apache.jsp
```
