### ISSUE TITLE
openapi: openapi does not generate valid parameter types

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-js#445]
The docs are generated with language-native parameter type names instead of openapi-specced names. Examples:

generated from Python AppMaps:
```yaml
        - name: secret
          in: path
          schema:
            type: builtins.str
          required: true
        - name: thumbnail
          in: query
          schema:
            type: builtins.bool
```

generated from Java AppMaps:
```yaml
        - name: id
          in: path
          schema:
            type: java.lang.string
          required: true
```

Valid types for these two examples are `boolean`, `string`.
